# -*- coding: utf-8 -*-
"""portfoliomanager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167Ca20whuCIUJIpeMd4R9tmOnwKbn-5c
"""

portfolio = {
    "RELIANCE.NS": 2450,
    "TCS.NS": 3850,
    "INFY.NS": 1750,
    "HDFCBANK.NS": 1650,
    "ICICIBANK.NS": 1250,
    "SBIN.NS": 820,
    "ITC.NS": 480,
    "BHARTIARTL.NS": 1650,
    "LT.NS": 3650,
    "ADANIENT.NS": 2500
}